package dukes.greeting;

// Make Greeting a Jakarta Persistence Entity that is not Cacheable
public class Greeting {

    /**
     * Helpful documentation:
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/entity
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/cacheable
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/id
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/generatedvalue
     * https://jakarta.ee/specifications/platform/10/apidocs/jakarta/persistence/generationtype
     */

    // Add a field called id as primary key. Use autogenerated UUIDs for the primary key
    // Add a field called message. Use String as type for the field

    // Getters and Setters
}
