package dukes.greeting;

// Make Greeting a Jakarta Persistence Entity that is not Cacheable
public class Greeting {

    // Add a field called id as primary key. Use autogenerated UUIDs for the primary key
    // Add a field called message. Use String as type for the field

    // Getters and Setters
}
